package com.niv.security.Controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.niv.security.model.User;
import com.niv.security.model.UserRequest;
import com.niv.security.model.UserResponse;
import com.niv.security.service.IUserService;
import com.niv.security.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserController {

	@Autowired
	private IUserService service;
	
	@Autowired
	private JwtUtil util;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	@PostMapping("/save")	
	public ResponseEntity<String> saveUser(@RequestBody User user){
		Integer userId = service.saveUser(user);
		String msg = "User '"+userId+"' saved..";
		return ResponseEntity.ok(msg);
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
						userRequest.getUsername(),
						userRequest.getPassword()));
		String token = util.generateToken(userRequest.getUsername());
		return ResponseEntity.ok(new UserResponse(token,"Success!! Generated By Nivrutti"));
	}
	
	
}
